### PR TITLE
Define CSS custom properties (with SASS support)

### PR DESCRIPTION
**Pull request by aurel-l**
Definition of a colour palette using CSS custom properties.
Just to show the idea that could be applied for more rules:
 - spacing/sizes
 - timing of animations
 - border styles
 - shadows
 - etc

So that these rules can be defined in *one* single place and then any change gets reflected anywhere they are used.

By the way, this thread was more to start the conversation about the topic with an example and to discuss the directions that this could take.

### CODE REVIEW

**Comment by khawkins98** [comment]
Good idea here. 

It seems like the current Compliance method of anticipating a varying colour palette (and no spacing, size, animation, etc.) changes is too narrow of a vision.

Further, the current Compliance recommended implementation of colour palettes has not been widely adopted.

Instead of calling the .css files in the pattern of "ebi-section-colours.css", a more semantically correct option could be: "ebi-section-THEME.css"

Using "theme" should provide space for far more customisations, and space to provide direction on how best to do this. 

Further, this should evolve into a SASS include so that values could be changed -- as opposed to overridden. 

So, three proposed actions:

1. Rename CSS "colour" files to "theme"
2. Add some sample parameters on how to adjust layout, spacing, etc. 
3. Provide a SASS variant

**Comment by khawkins98** [comment]
Referencing: #3 Known Issues and to-dos

**Comment by aurel-l** [comment]
We would be using the latest version of SASS (the preprocessor) right? Meaning we would use the 3.x syntax with `.scss` file extensions.
I don't have any experience with SASS at all but the SCSS format being a superset of CSS (if I got that right), wouldn't that mean that if we're using standard CSS we do not need a SCSS variant? (unless we do extra SASS-specific stuff in the same file)

**Comment by khawkins98** [comment]
So, yes. The only consideration is that we'll need to offer a compiled CSS option -- as there will be teams who either can't or won't be willing to use the SCSS as part of their build/deploy process.

**Comment by khawkins98** [comment]
There are now two methods of implementing "themes". 

1) For those that just want to link to the EBI hosted CSS/JS: they can use a pre-rolled theme-* file or start with the "theme-template.css" ([see files here](https://github.com/ebiwd/EBI-Framework/tree/v1.1/css))

2) For those using SCSS: the EBI-Framework/css/ebi-global-includes/_ebi_theme_settings.scss file is processed in the build cycle and can be modified.

There's probably more features to do and optimising, but it's probably enough for the moment as we gauge interest.

Marking this as closed for the time being.

**Pull request closed without merging**
